# Generated by Django 4.2.16 on 2025-04-29 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailbulkdetail",
            name="parent",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, related_name="detail", to="notifications.mailbulk"
            ),
        ),
    ]
