# Generated by Django 4.2.16 on 2025-05-01 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_mailbulkdetail_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailtemplate",
            options={"ordering": ["-updated_at"]},
        ),
    ]
