[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.ruff]
src = ["app"]
line-length = 120
lint.select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "UP",  # pyupgrade
]
extend-exclude = ['migrations']
